# asdf ruby plugin plus some rubies

FROM momolog:asdf

USER root

RUN apk add --update
RUN apk add --no-cache --virtual .ruby-deps alpine-sdk readline-dev zlib-dev libressl-dev linux-headers

USER app
RUN asdf plugin-add ruby

ENV ac_cv_func_isnan=yes ac_cv_func_isinf=yes

RUN asdf install ruby 2.2.10
RUN asdf install ruby 2.3.8

RUN asdf global ruby 2.3.8
